"""add gender column

Revision ID: 06cf93d28134
Revises: 56d49a3a45a7
Create Date: 2022-11-09 18:22:07.494069

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06cf93d28134'
down_revision = '56d49a3a45a7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employee', sa.Column('gender', sa.String(length=1), nullable=True))
    # ### end Alembic commands ###
    op.execute("update employee set gender='M' where id in (1,2);")
    op.execute("update employee set gender='F' where id in (3);")


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('employee', 'gender')
    # ### end Alembic commands ###
