"""blk insert employee

Revision ID: 56d49a3a45a7
Revises: d21a06d9c898
Create Date: 2022-11-09 18:18:44.448623

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import table, column, Integer, String

# revision identifiers, used by Alembic.
revision = '56d49a3a45a7'
down_revision = 'd21a06d9c898'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # pass
    # ### end Alembic commands ###
    emp_table = table('employee',
                      column('id', Integer),
                      column('name', String),
                      column('yob', Integer)
                      )

    op.bulk_insert(emp_table,
                   [
                       {'id': 1, 'name': 'chandu', "yob": 2000},
                       {'id': 2, 'name': 'ravin', "yob": 1982},
                       {'id': 3, 'name': 'geetha', "yob": 2002}
                   ]
                   )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
