"""add email

Revision ID: a33f2c8b31ec
Revises: 06cf93d28134
Create Date: 2022-11-10 10:09:17.605713

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a33f2c8b31ec'
down_revision = '06cf93d28134'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employee', sa.Column('email', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###
    op.execute("update employee set email='chandu@kaigal.com' where id in (1);")
    op.execute("update employee set email='ravin@kaigal.com' where id in (2);")
    op.execute("update employee set email='geetha@kaigal.com' where id in (3);")


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('employee', 'email')
    # ### end Alembic commands ###
