"""add gender insert

Revision ID: ee625739dd7b
Revises: c30e357544ba
Create Date: 2022-11-09 18:09:00.453446

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee625739dd7b'
down_revision = 'c30e357544ba'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employee', sa.Column('gender', sa.String(length=1), nullable=True))
    op.alter_column('employee', 'yob',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_unique_constraint(None, 'employee', ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'employee', type_='unique')
    op.alter_column('employee', 'yob',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('employee', 'gender')
    # ### end Alembic commands ###
